{{- if .Values.github.pullSecret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.github.pullSecret.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "df-nec2.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\":{\"%s\":{\"username\": \"%s\",\"password\":\"%s\",\"auth\":\"%s\"}}}" .Values.github.pullSecret.registry .Values.github.pullSecret.username (required "A valid .Values.github.pullSecret.token (CONTAINER_REGISTRY_PAT) is required! Use --set github.pullSecret.token=..." .Values.github.pullSecret.token) (printf "%s:%s" .Values.github.pullSecret.username .Values.github.pullSecret.token | b64enc) | b64enc }}
{{- end }}
