{{- if and .Values.openshift.anyuidScc (not .Values.argocd) }}
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: {{ include "df-nec2.fullname" . }}
  labels:
    {{- include "df-nec2.labels" . | nindent 4 }}
allowHostDirVolumePlugin: false
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegeEscalation: true
allowPrivilegedContainer: false
allowedCapabilities:
- NET_ADMIN
defaultAddCapabilities:
- NET_ADMIN
requiredDropCapabilities:
- MKNOD
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
seccompProfiles:
- unconfined
fsGroup:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
volumes:
- configMap
- downwardAPI
- emptyDir
- persistentVolumeClaim
- projected
- secret
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: system:openshift:scc:{{ include "df-nec2.fullname" . }}
  labels:
    {{- include "df-nec2.labels" . | nindent 4 }}
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - {{ include "df-nec2.fullname" . }}
  resources:
  - securitycontextconstraints
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "df-nec2.fullname" . }}-scc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "df-nec2.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:{{ include "df-nec2.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "df-nec2.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
