appName: basic-app
namespace: basic-app

replicaCount: 1

image:
  registry: ""
  repository: ""
  tag: "05cf216"
  pullPolicy: Always

service:
  port: 3000

route:
  host: ""

appConfig:
  js: ""
  json: ""
  yaml: ""
