apiVersion: v2
name: spectrogram-app-pomerium
description: Spectrogram application with mock sd server sidecar and Pomerium ingress (TLS via cert-manager)
type: application
version: 1.0.18
appVersion: "1.0.18"
