apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.appName }}-infra-repo
  namespace: {{ .Values.argoCDNamespace }}
  labels:
    argocd.argoproj.io/secret-type: repository
  annotations:
    managed-by: argocd.argoproj.io
type: Opaque
stringData:
  type: git
  url: {{ .Values.repository.url }}
  project: default
  githubAppID: {{ .Values.repository.githubAppID | quote }}
  githubAppInstallationID: {{ .Values.repository.githubAppInstallationID | quote }}
  githubAppPrivateKey: |
{{ .Values.repository.githubAppPrivateKey | indent 4 }}
