appName: basic-app
namespace: basic-app

replicaCount: 1

image:
  registry: ""
  repository: ""
  tag: "ab1c8b3"
  pullPolicy: Always

nginx:
  image: nginx:alpine

caCert: ""

service:
  port: 3000
  nginxPort: 8443

route:
  host: ""
