appName: basic-app
namespace: basic-app

replicaCount: 1

image:
  registry: ""
  repository: ""
  tag: "6f57266"
  pullPolicy: Always

nginx:
  image: nginx:alpine

caCert: ""

acmeDirectoryUrl: "-"
acmeIssuerName: "internal-ca"

nginxCaCert: ""
nginxCaKey: ""

service:
  port: 3000
  nginxPort: 8443

route:
  host: ""
