apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.appName }}-ca
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  ca-cert.pem: {{ required "caCert is required" .Values.caCert | b64enc }}
