apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.appName }}-nginx-config
  namespace: {{ .Values.namespace }}
data:
  nginx.conf: |
    pid /tmp/nginx.pid;
    events {}
    http {
      client_body_temp_path /tmp/nginx_client_temp;
      proxy_temp_path        /tmp/nginx_proxy_temp;
      fastcgi_temp_path      /tmp/nginx_fastcgi_temp;
      uwsgi_temp_path        /tmp/nginx_uwsgi_temp;
      scgi_temp_path         /tmp/nginx_scgi_temp;

      server {
        listen {{ .Values.service.nginxPort }} ssl;

        ssl_certificate     /etc/nginx/ssl/tls.crt;
        ssl_certificate_key /etc/nginx/ssl/tls.key;

        ssl_client_certificate /etc/nginx/ssl/ca-cert.pem;
        ssl_verify_client      on;

        location / {
          proxy_pass http://{{ .Values.appName }}:{{ .Values.service.port }};
          proxy_set_header Host               $host;
          proxy_set_header X-Real-IP          $remote_addr;
          proxy_set_header X-SSL-Client-Verify $ssl_client_verify;
          proxy_set_header X-SSL-Client-DN    $ssl_client_s_dn;
          proxy_set_header X-SSL-Client-Cert  $ssl_client_escaped_cert;
        }
      }
    }
