{{- if .Values.githubToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "df-sim.fullname" . }}-ghcr
  labels:
    {{- include "df-sim.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\",\"auth\":\"%s\"}}}" .Values.image.registry .Values.githubUsername .Values.githubToken (printf "%s:%s" .Values.githubUsername .Values.githubToken | b64enc) | b64enc }}
{{- end }}
