appName: basic-app
namespace: basic-app

replicaCount: 1

image:
  registry: ghcr.io
  repository: tamfrost/basic-app
  tag: "03207d6"
  pullPolicy: Always

service:
  port: 3000

route:
  enabled: false
  host: ""
