apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.appName }}-client-secret
  namespace: {{ .Values.namespace }}
stringData:
  clientsecret: {{ required "oauth2Proxy.clientSecret is required" .Values.oauth2Proxy.clientSecret | quote }}
