{{- if not .Values.argocd.github.token }}
{{- fail "A valid .Values.argocd.github.token is required! Use --set argocd.github.token=YOUR_TOKEN" }}
{{- end }}
{{- if not .Values.argocd.github.username }}
{{- fail "A valid .Values.argocd.github.username is required!" }}
{{- end }}
{{- if not .Values.argocd.application.source.repoURL }}
{{- fail "A valid .Values.argocd.application.source.repoURL is required!" }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.argocd.application.name }}-ghcr-credentials
  namespace: {{ .Values.argocd.namespace }}
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  type: helm
  name: ghcr
  url: {{ .Values.argocd.application.source.repoURL }}
  enableOCI: "true"
  username: {{ .Values.argocd.github.username }}
  password: {{ .Values.argocd.github.token }}
