{{- if not .Values.argocd.infraRepo.token }}
{{- fail "A valid .Values.argocd.infraRepo.token is required! Use --set argocd.infraRepo.token=YOUR_TOKEN" }}
{{- end }}
{{- if not .Values.argocd.application.source.repoURL }}
{{- fail "A valid .Values.argocd.application.source.repoURL is required!" }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.argocd.application.name }}-infra-repo-credentials
  namespace: {{ .Values.argocd.namespace }}
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  type: git
  url: {{ .Values.argocd.application.source.repoURL }}
  username: {{ .Values.argocd.infraRepo.username | default "x-access-token" }}
  password: {{ .Values.argocd.infraRepo.token }}
