appName: basic-app
namespace: basic-app

replicaCount: 1

image:
  registry: ""
  repository: ""
  tag: "6a53247"
  pullPolicy: Always

service:
  port: 3000

route:
  enabled: false
  host: ""

appConfig:
  js: ""
  json: ""
  yaml: ""
