{{- if .Values.route.enabled -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "df-proxy.fullname" . }}
  labels:
    {{- include "df-proxy.labels" . | nindent 4 }}
spec:
  {{- if .Values.route.host }}
  host: {{ .Values.route.host }}
  {{- end }}
  {{- if .Values.route.path }}
  path: {{ .Values.route.path }}
  {{- end }}
  to:
    kind: Service
    name: {{ include "df-proxy.fullname" . }}
    weight: 100
  port:
    targetPort: http
  {{- if .Values.route.tls.enabled }}
  tls:
    termination: {{ .Values.route.tls.termination | default "edge" }}
    insecureEdgeTerminationPolicy: {{ .Values.route.tls.insecureEdgeTerminationPolicy | default "Redirect" }}
  {{- end }}
  wildcardPolicy: None
{{- end }}
