{{- if .Values.route.enabled -}}
{{- $fullName := include "df-sim.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "df-sim.labels" . | nindent 4 }}
  {{- with .Values.route.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.route.host }}
  host: {{ .Values.route.host }}
  {{- end }}
  {{- if .Values.route.path }}
  path: {{ .Values.route.path }}
  {{- end }}
  to:
    kind: Service
    name: {{ $fullName }}
    weight: 100
  port:
    targetPort: http
  {{- if .Values.route.tls.enabled }}
  tls:
    termination: {{ .Values.route.tls.termination }}
    {{- if eq .Values.route.tls.termination "reencrypt" }}
    destinationCACertificate: {{ .Values.route.tls.destinationCACertificate }}
    {{- end }}
    {{- if .Values.route.tls.insecureEdgeTerminationPolicy }}
    insecureEdgeTerminationPolicy: {{ .Values.route.tls.insecureEdgeTerminationPolicy }}
    {{- end }}
  {{- end }}
  wildcardPolicy: None
{{- end }}
